// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7WQLuR_2ocoTC-jHp76hegCY-eSepE_I',
    appId: '1:814575294638:web:2948f1b6551bbf347cf53f',
    messagingSenderId: '814575294638',
    projectId: 'hybriidgrocery',
    authDomain: 'hybriidgrocery.firebaseapp.com',
    storageBucket: 'hybriidgrocery.appspot.com',
    measurementId: 'G-D2E4EJBRL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESWBDs-Mv776OEStlDf9UCvU577uPndo',
    appId: '1:596344722417:android:9ab1de9a78c9b7c1386a50',
    messagingSenderId: '596344722417',
    projectId: 'hbappsgrocery',
    storageBucket: 'hbappsgrocery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNosFy13EN_6O3_kQLcm99QfUaUpVIf4',
    appId: '1:596344722417:ios:9b13816e822ebed4386a50',
    messagingSenderId: '596344722417',
    projectId: 'hbappsgrocery',
    storageBucket: 'hbappsgrocery.firebasestorage.app',
    iosBundleId: 'com.example.officialgrocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAolDBW1jfXcgzYC6dM9v3CA29ucy1m5j8',
    appId: '1:814575294638:ios:d7486adcd9793cb27cf53f',
    messagingSenderId: '814575294638',
    projectId: 'hybriidgrocery',
    storageBucket: 'hybriidgrocery.appspot.com',
    iosBundleId: 'com.example.officialgrocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7WQLuR_2ocoTC-jHp76hegCY-eSepE_I',
    appId: '1:814575294638:web:e30d8a71f7d0199e7cf53f',
    messagingSenderId: '814575294638',
    projectId: 'hybriidgrocery',
    authDomain: 'hybriidgrocery.firebaseapp.com',
    storageBucket: 'hybriidgrocery.appspot.com',
    measurementId: 'G-1JV608T14K',
  );
}